name: virustotal

on:
  workflow_call:

jobs:
  vt-scan:
    name: Scan EFI with VirusTotal
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compress EFI to EFI.zip
        run: zip -r -X EFI.zip EFI

      - name: Set update_body_release if event type is release
        run: |
          if [[ $GITHUB_EVENT_NAME == 'release' ]]; then
              echo "update_release_body=true" >> "$GITHUB_ENV"
          else
              echo "update_release_body=false" >> "$GITHUB_ENV"
          fi
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            EFI.zip
          request_rate: 4
          update_release_body: ${{env.update_release_body}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
